version: '3.9'

services:
  app2:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db2
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SCADA_DB_NAME=${SCADA_DB_NAME}
      - SCADA_DB_USER=${SCADA_DB_USER}
      - SCADA_DB_PASS=${SCADA_DB_PASS}
      - SCADA_DB_SERVER=${SCADA_DB_SERVER}
      - SCADA_DB_PORT=${SCADA_DB_PORT}

    depends_on:
      - db2

  db2:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app2
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
  
volumes:
  postgres-data:
  static-data:
