# Generated by Django 3.2.16 on 2022-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
