# Generated by Django 3.2.16 on 2022-11-25 17:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221125_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generators', to='api.plant')),
            ],
            options={
                'unique_together': {('plant', 'name')},
                'index_together': {('plant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='ScadaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scada_pid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=360, null=True)),
                ('out_value', models.IntegerField(default=0)),
                ('generator', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='scada_points', to='api.generator')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('priority', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='api.priority')),
                ('scada_point', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='api.scadapoint')),
            ],
        ),
    ]
